# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :beta_es do
    upload_to_play_store(track: 'beta')
  end

  lane :beta_us do
    upload_to_play_store(track: 'beta')
  end

  lane :promote_es do
    upload_to_play_store(track: 'beta',
      track_promote_to: 'production',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  lane :promote_us do
    upload_to_play_store(track: 'beta',
      track_promote_to: 'production',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
